name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: shelmangroup-default
    env:
      ImageOS: ubuntu22
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: "1.14"

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: go version
      - run: npm version
      - run: java -version
      - run: python --version
